site_name: WeeChad
site_url: https://dyne.org/weechad
site_description: curl -Ls dyne.org/weechad/setup | NICK=yournick bash

theme:
  name: material
  logo: images/weechad_ascii_logo.png
  favicon: images/favicon.svg

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://toot.community/@dyne
    - icon: fontawesome/brands/github
      link: https://github.com/dyne/weechad

nav:
  - WeeChat: https://weechat.org
  - DarkIRC: https://news.dyne.org/howto_darkfi_1-connect_to_darkirc/
  - Libera: https://libera.chat/
  - DarkFI: https://dark.fi
  - Tomb: https://dyne.org/tomb
  - Dyne.org: https://dyne.org

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - social
  - privacy
  - search:
      enabled: false
